    services:
      qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        ports:
          - "6333:6333" # REST API
          - "6334:6334" # gRPC API
        volumes:
          - ./qdrant_storage:/qdrant/storage # Persistent storage for Qdrant data
        environment:
          QDRANT__SERVICE__HOST: "0.0.0.0"
          QDRANT__SERVICE__PORT: 6333
          QDRANT__SERVICE__GRPC_PORT: 6334
          QDRANT__STORAGE__PATH: "/qdrant/storage"